# Generated by Django 4.2.5 on 2023-09-24 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='categoryrelation',
            unique_together={('parent', 'child')},
        ),
        migrations.AlterModelTable(
            name='category',
            table='km_category',
        ),
        migrations.AlterModelTable(
            name='categoryrelation',
            table='km_category_relation',
        ),
    ]
