# Generated by Django 4.1.7 on 2023-10-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_map', '0003_uniquefile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquefile',
            name='content_type',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
