# Generated by Django 4.1.7 on 2023-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_map', '0004_alter_uniquefile_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfile',
            name='unique_file_digest',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
