# Generated by Django 4.1.7 on 2023-10-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_map', '0005_managedfile_unique_file_digest'),
    ]

    operations = [
        # Step 1: Convert unique_file_digest into a ForeignKey
        migrations.AlterField(
            model_name='managedfile',
            name='unique_file_digest',
            field=models.ForeignKey(
                to='knowledge_map.UniqueFile',
                to_field='digest',
                on_delete=models.CASCADE,
                related_name='managed_files',
                db_column='unique_file_digest'
            ),
        ),
        # Step 2: Remove the old ForeignKey (optional, can be done in a separate migration)
        migrations.RemoveField(
            model_name='managedfile',
            name='unique_file',
        ),
    ]
