# Generated by Django 4.1.7 on 2023-10-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_map', '0006_auto_20231007_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managedfile',
            old_name='unique_file_digest',
            new_name='unique_file',
        ),
    ]
