# Generated by Django 4.2.5 on 2023-10-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_map', '0002_category_created_at_category_updated_at_and_more'),
        ('knowledge_map', '0007_rename_unique_file_digest_managedfile_unique_file'),
    ]

    operations = [
    ]
