CREATE DATABASE IF NOT EXISTS `pkm` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'pkm'@'%' IDENTIFIED WITH mysql_native_password BY 'Hello123456_';
GRANT ALL PRIVILEGES ON *.* TO 'pkm'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;