apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkm
  namespace: geek-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pkm
      app.kubernetes.io/instance: pkm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pkm
        app.kubernetes.io/instance: pkm
    spec:
      containers:
        - name: pkm-container
          image: "jameszhan/pkm:0.0.20"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/app/.env"
              subPath: .env
              name: pkm-env-vol
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: Host
                  value: pkm.cluster.local:8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              httpHeaders:
                - name: Host
                  value: pkm.cluster.local:8000
          resources:
            requests:
              cpu: 2000m
              memory: 2048Mi
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "settings.production"
      volumes:
        - name: pkm-env-vol
          configMap:
            name: pkm-env