# Generated by Django 4.1.7 on 2023-09-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='author',
            name='descriptor',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.publisher'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'nationality', 'descriptor')},
        ),
    ]
