# Generated by Django 4.1.7 on 2023-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_author_options_alter_author_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('isbn', 'version')},
        ),
    ]
