# Generated by Django 4.1.7 on 2023-09-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_version_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='alias',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
