# Generated by Django 4.1.7 on 2023-10-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiouniquefile',
            name='status',
            field=models.CharField(choices=[('DELETED', '已删除'), ('DISABLED', '禁止访问'), ('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='docuniquefile',
            name='status',
            field=models.CharField(choices=[('DELETED', '已删除'), ('DISABLED', '禁止访问'), ('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='ebookuniquefile',
            name='status',
            field=models.CharField(choices=[('DELETED', '已删除'), ('DISABLED', '禁止访问'), ('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='imageuniquefile',
            name='status',
            field=models.CharField(choices=[('DELETED', '已删除'), ('DISABLED', '禁止访问'), ('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='pdfuniquefile',
            name='status',
            field=models.CharField(choices=[('DELETED', '已删除'), ('DISABLED', '禁止访问'), ('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='textuniquefile',
            name='status',
            field=models.CharField(choices=[('DELETED', '已删除'), ('DISABLED', '禁止访问'), ('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='videouniquefile',
            name='status',
            field=models.CharField(choices=[('DELETED', '已删除'), ('DISABLED', '禁止访问'), ('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档')], db_index=True, default='LISTING', max_length=16),
        ),
    ]
