# Generated by Django 4.1.7 on 2023-10-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_map', '0007_rename_unique_file_digest_managedfile_unique_file'),
        ('webfs', '0002_alter_audiouniquefile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiouniquefile',
            name='categories',
            field=models.ManyToManyField(to='knowledge_map.category'),
        ),
        migrations.AddField(
            model_name='audiouniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOK', '图书'), ('PAPER', '论文'), ('SLIDES', '演讲稿'), ('LECTURE', '课件'), ('SPREADSHEET', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTO', '照片'), ('IMAGE', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('MOVIE', '影片'), ('VIDEO', '视频'), ('MANUAL', '手册'), ('DOCUMENT', '文档'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=16),
        ),
        migrations.AddField(
            model_name='docuniquefile',
            name='categories',
            field=models.ManyToManyField(to='knowledge_map.category'),
        ),
        migrations.AddField(
            model_name='docuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOK', '图书'), ('PAPER', '论文'), ('SLIDES', '演讲稿'), ('LECTURE', '课件'), ('SPREADSHEET', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTO', '照片'), ('IMAGE', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('MOVIE', '影片'), ('VIDEO', '视频'), ('MANUAL', '手册'), ('DOCUMENT', '文档'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=16),
        ),
        migrations.AddField(
            model_name='ebookuniquefile',
            name='categories',
            field=models.ManyToManyField(to='knowledge_map.category'),
        ),
        migrations.AddField(
            model_name='ebookuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOK', '图书'), ('PAPER', '论文'), ('SLIDES', '演讲稿'), ('LECTURE', '课件'), ('SPREADSHEET', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTO', '照片'), ('IMAGE', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('MOVIE', '影片'), ('VIDEO', '视频'), ('MANUAL', '手册'), ('DOCUMENT', '文档'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=16),
        ),
        migrations.AddField(
            model_name='imageuniquefile',
            name='categories',
            field=models.ManyToManyField(to='knowledge_map.category'),
        ),
        migrations.AddField(
            model_name='imageuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOK', '图书'), ('PAPER', '论文'), ('SLIDES', '演讲稿'), ('LECTURE', '课件'), ('SPREADSHEET', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTO', '照片'), ('IMAGE', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('MOVIE', '影片'), ('VIDEO', '视频'), ('MANUAL', '手册'), ('DOCUMENT', '文档'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=16),
        ),
        migrations.AddField(
            model_name='pdfuniquefile',
            name='categories',
            field=models.ManyToManyField(to='knowledge_map.category'),
        ),
        migrations.AddField(
            model_name='pdfuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOK', '图书'), ('PAPER', '论文'), ('SLIDES', '演讲稿'), ('LECTURE', '课件'), ('SPREADSHEET', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTO', '照片'), ('IMAGE', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('MOVIE', '影片'), ('VIDEO', '视频'), ('MANUAL', '手册'), ('DOCUMENT', '文档'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=16),
        ),
        migrations.AddField(
            model_name='textuniquefile',
            name='categories',
            field=models.ManyToManyField(to='knowledge_map.category'),
        ),
        migrations.AddField(
            model_name='textuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOK', '图书'), ('PAPER', '论文'), ('SLIDES', '演讲稿'), ('LECTURE', '课件'), ('SPREADSHEET', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTO', '照片'), ('IMAGE', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('MOVIE', '影片'), ('VIDEO', '视频'), ('MANUAL', '手册'), ('DOCUMENT', '文档'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=16),
        ),
        migrations.AddField(
            model_name='videouniquefile',
            name='categories',
            field=models.ManyToManyField(to='knowledge_map.category'),
        ),
        migrations.AddField(
            model_name='videouniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOK', '图书'), ('PAPER', '论文'), ('SLIDES', '演讲稿'), ('LECTURE', '课件'), ('SPREADSHEET', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTO', '照片'), ('IMAGE', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('MOVIE', '影片'), ('VIDEO', '视频'), ('MANUAL', '手册'), ('DOCUMENT', '文档'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=16),
        ),
    ]
