# Generated by Django 4.1.7 on 2023-10-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfs', '0003_audiouniquefile_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiouniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOKS', '图书'), ('PERIODICALS', '期刊'), ('MANUALS', '手册'), ('EDUCATIONAL_MATERIALS', '教育材料'), ('REPORTS', '报告'), ('PROMOTIONS', '宣传材料'), ('ONLINE_CONTENT', '在线内容'), ('SLIDES', '演讲稿'), ('SPREADSHEETS', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTOS', '照片'), ('IMAGES', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('VIDEO', '视频'), ('MOVIES', '影片'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='docuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOKS', '图书'), ('PERIODICALS', '期刊'), ('MANUALS', '手册'), ('EDUCATIONAL_MATERIALS', '教育材料'), ('REPORTS', '报告'), ('PROMOTIONS', '宣传材料'), ('ONLINE_CONTENT', '在线内容'), ('SLIDES', '演讲稿'), ('SPREADSHEETS', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTOS', '照片'), ('IMAGES', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('VIDEO', '视频'), ('MOVIES', '影片'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='ebookuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOKS', '图书'), ('PERIODICALS', '期刊'), ('MANUALS', '手册'), ('EDUCATIONAL_MATERIALS', '教育材料'), ('REPORTS', '报告'), ('PROMOTIONS', '宣传材料'), ('ONLINE_CONTENT', '在线内容'), ('SLIDES', '演讲稿'), ('SPREADSHEETS', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTOS', '照片'), ('IMAGES', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('VIDEO', '视频'), ('MOVIES', '影片'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='imageuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOKS', '图书'), ('PERIODICALS', '期刊'), ('MANUALS', '手册'), ('EDUCATIONAL_MATERIALS', '教育材料'), ('REPORTS', '报告'), ('PROMOTIONS', '宣传材料'), ('ONLINE_CONTENT', '在线内容'), ('SLIDES', '演讲稿'), ('SPREADSHEETS', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTOS', '照片'), ('IMAGES', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('VIDEO', '视频'), ('MOVIES', '影片'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='pdfuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOKS', '图书'), ('PERIODICALS', '期刊'), ('MANUALS', '手册'), ('EDUCATIONAL_MATERIALS', '教育材料'), ('REPORTS', '报告'), ('PROMOTIONS', '宣传材料'), ('ONLINE_CONTENT', '在线内容'), ('SLIDES', '演讲稿'), ('SPREADSHEETS', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTOS', '照片'), ('IMAGES', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('VIDEO', '视频'), ('MOVIES', '影片'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='textuniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOKS', '图书'), ('PERIODICALS', '期刊'), ('MANUALS', '手册'), ('EDUCATIONAL_MATERIALS', '教育材料'), ('REPORTS', '报告'), ('PROMOTIONS', '宣传材料'), ('ONLINE_CONTENT', '在线内容'), ('SLIDES', '演讲稿'), ('SPREADSHEETS', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTOS', '照片'), ('IMAGES', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('VIDEO', '视频'), ('MOVIES', '影片'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='videouniquefile',
            name='resource_type',
            field=models.CharField(choices=[('BOOKS', '图书'), ('PERIODICALS', '期刊'), ('MANUALS', '手册'), ('EDUCATIONAL_MATERIALS', '教育材料'), ('REPORTS', '报告'), ('PROMOTIONS', '宣传材料'), ('ONLINE_CONTENT', '在线内容'), ('SLIDES', '演讲稿'), ('SPREADSHEETS', '表格'), ('NOTES', '笔记'), ('CODE', '代码'), ('PHOTOS', '照片'), ('IMAGES', '图片'), ('MUSIC', '音乐'), ('AUDIO', '音频'), ('VIDEO', '视频'), ('MOVIES', '影片'), ('OTHER', '其他资源')], db_index=True, default='OTHER', max_length=32),
        ),
    ]
