# Generated by Django 4.1.7 on 2023-10-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfs', '0005_series_audiouniquefile_series_docuniquefile_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rule', models.CharField(blank=True, max_length=768, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='audiouniquefile',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='docuniquefile',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ebookuniquefile',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='imageuniquefile',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='pdfuniquefile',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='textuniquefile',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='videouniquefile',
            name='rating',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='audiouniquefile',
            name='levels',
            field=models.ManyToManyField(blank=True, to='webfs.level'),
        ),
        migrations.AddField(
            model_name='docuniquefile',
            name='levels',
            field=models.ManyToManyField(blank=True, to='webfs.level'),
        ),
        migrations.AddField(
            model_name='ebookuniquefile',
            name='levels',
            field=models.ManyToManyField(blank=True, to='webfs.level'),
        ),
        migrations.AddField(
            model_name='imageuniquefile',
            name='levels',
            field=models.ManyToManyField(blank=True, to='webfs.level'),
        ),
        migrations.AddField(
            model_name='pdfuniquefile',
            name='levels',
            field=models.ManyToManyField(blank=True, to='webfs.level'),
        ),
        migrations.AddField(
            model_name='textuniquefile',
            name='levels',
            field=models.ManyToManyField(blank=True, to='webfs.level'),
        ),
        migrations.AddField(
            model_name='videouniquefile',
            name='levels',
            field=models.ManyToManyField(blank=True, to='webfs.level'),
        ),
    ]
