# Generated by Django 4.1.7 on 2023-10-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webfs', '0006_level_audiouniquefile_rating_docuniquefile_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiouniquefile',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfs.audiouniquefile', to_field='digest'),
        ),
        migrations.AddField(
            model_name='audiouniquefile',
            name='storage_status',
            field=models.CharField(choices=[('PENDING', '等待处理'), ('STORED', '已存储'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档'), ('DISABLED', '禁止访问'), ('DELETED', '已删除')], db_index=True, default='STORED', max_length=16),
        ),
        migrations.AddField(
            model_name='docuniquefile',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfs.docuniquefile', to_field='digest'),
        ),
        migrations.AddField(
            model_name='docuniquefile',
            name='storage_status',
            field=models.CharField(choices=[('PENDING', '等待处理'), ('STORED', '已存储'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档'), ('DISABLED', '禁止访问'), ('DELETED', '已删除')], db_index=True, default='STORED', max_length=16),
        ),
        migrations.AddField(
            model_name='ebookuniquefile',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfs.ebookuniquefile', to_field='digest'),
        ),
        migrations.AddField(
            model_name='ebookuniquefile',
            name='storage_status',
            field=models.CharField(choices=[('PENDING', '等待处理'), ('STORED', '已存储'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档'), ('DISABLED', '禁止访问'), ('DELETED', '已删除')], db_index=True, default='STORED', max_length=16),
        ),
        migrations.AddField(
            model_name='imageuniquefile',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfs.imageuniquefile', to_field='digest'),
        ),
        migrations.AddField(
            model_name='imageuniquefile',
            name='storage_status',
            field=models.CharField(choices=[('PENDING', '等待处理'), ('STORED', '已存储'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档'), ('DISABLED', '禁止访问'), ('DELETED', '已删除')], db_index=True, default='STORED', max_length=16),
        ),
        migrations.AddField(
            model_name='pdfuniquefile',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfs.pdfuniquefile', to_field='digest'),
        ),
        migrations.AddField(
            model_name='pdfuniquefile',
            name='storage_status',
            field=models.CharField(choices=[('PENDING', '等待处理'), ('STORED', '已存储'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档'), ('DISABLED', '禁止访问'), ('DELETED', '已删除')], db_index=True, default='STORED', max_length=16),
        ),
        migrations.AddField(
            model_name='textuniquefile',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfs.textuniquefile', to_field='digest'),
        ),
        migrations.AddField(
            model_name='textuniquefile',
            name='storage_status',
            field=models.CharField(choices=[('PENDING', '等待处理'), ('STORED', '已存储'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档'), ('DISABLED', '禁止访问'), ('DELETED', '已删除')], db_index=True, default='STORED', max_length=16),
        ),
        migrations.AddField(
            model_name='videouniquefile',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webfs.videouniquefile', to_field='digest'),
        ),
        migrations.AddField(
            model_name='videouniquefile',
            name='storage_status',
            field=models.CharField(choices=[('PENDING', '等待处理'), ('STORED', '已存储'), ('COLLECTED', '已收藏'), ('ARCHIVED', '已归档'), ('DISABLED', '禁止访问'), ('DELETED', '已删除')], db_index=True, default='STORED', max_length=16),
        ),
        migrations.AlterField(
            model_name='audiouniquefile',
            name='status',
            field=models.CharField(choices=[('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='docuniquefile',
            name='status',
            field=models.CharField(choices=[('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='ebookuniquefile',
            name='status',
            field=models.CharField(choices=[('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='imageuniquefile',
            name='status',
            field=models.CharField(choices=[('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='pdfuniquefile',
            name='status',
            field=models.CharField(choices=[('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='textuniquefile',
            name='status',
            field=models.CharField(choices=[('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版')], db_index=True, default='LISTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='videouniquefile',
            name='status',
            field=models.CharField(choices=[('LISTING', '上架中'), ('LISTED', '已上架'), ('DELISTED', '已下架'), ('DRAFT', '草稿'), ('FORTHCOMING', '待出版'), ('PUBLISHED', '已出版')], db_index=True, default='LISTING', max_length=16),
        ),
    ]
